cpdef object numpy_ascontiguousarray(object arr)
cpdef object numpy_ravel_C(object arr)
cdef object numpy_dbl_1d(double * x, size_t n1, bint copy)
cdef object numpy_dbl_2d(double * x, size_t n1, size_t n2, bint copy)
cdef object numpy_dbl_3d(double * x, size_t n1, size_t n2, size_t n3, bint copy)
cdef object numpy_lng_1d(long * x, size_t n1, bint copy)
cdef object numpy_lng_2d(long * x, size_t n1, size_t n2, bint copy)
cdef object numpy_uch_1d(unsigned char * x, size_t n1, bint copy)
cdef object numpy_cmpl_1d(double complex * x, size_t n1, bint copy)